
spring:
  application:
    name: 'service-discovery'
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

server:
  port: ${PORT:8761}