
spring:
  application:
    name: 'user-service-api'
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}