spring:
  application:
    name: 'emailservice'

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:pedromont436@gmail.com}
    password: ${MAIL_PASSWORD:qtbr ncmg qttl mzdz}
    protocol: ${MAIL_PROTOCOL:smtp}