spring:
  application:
    name: order-service-api
  profiles:
    active: 'dev'
  config:
    import: optional:configserver:http://localhost:8888
  
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost} 
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    connection-timeout: 10000